export enum RoutePathEnum {
  EDITAR_CENTRO_COSTOS = 'editar-centro-costos',
  GESTION_EMPRESA = 'gestion-empresa',
  CENTRO_COSTOS = 'centro-costos',
  FORMATOS_IMPRESION = 'formatos-impresion',
  EDITAR_FORMATO_IMPRESION = 'editar-formato-impresion',
  UNIDAD = 'unidad',
  EDITAR_UNIDAD = 'editar-unidad',
  OTROS_PRODUCTOS = 'otros-productos',
  EDITAR_OTRO_PRODUCTO = 'editar-otro-producto',
  GESTION_CLIENTE = 'gestion-cliente',
  DETALLE_CLIENTE = 'detalle-cliente',
  EDITAR_CLIENTE = 'editar-cliente',
  GESTION_CONTRATO_CLIENTE = 'gestion-contrato-cliente',
  EDITAR_CONTRATO_CLIENTE = 'editar-contrato-cliente',
  GESTION_PRODUCTO = 'gestion-producto',
  DETALLE_PRODUCTO = 'detalle-producto',
  EDITAR_PRODUCTO = 'editar-producto',
  EDITAR_RESOLUCION = 'editar-resolucion',
  EDITAR_RESOLUCION_SUCURSAL = 'editar-resolucion-sucursal',
}
