// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.Data;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127125216_Usuario")]
    partial class Usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DomainLayer.Models.CiudadModel", b =>
                {
                    b.Property<int>("CiudCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudCodigo"), 1L, 1);

                    b.Property<int>("CiudDepto")
                        .HasColumnType("int");

                    b.Property<bool?>("CiudEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CiudFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CiudFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CiudNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CiudCodigo");

                    b.HasIndex("CiudDepto");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("DomainLayer.Models.ClaseFacturaModel", b =>
                {
                    b.Property<int>("ClfaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClfaCodigo"), 1L, 1);

                    b.Property<bool?>("ClfaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ClfaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClfaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClfaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClfaCodigo");

                    b.ToTable("ClaseFactura");
                });

            modelBuilder.Entity("DomainLayer.Models.ClasJuridicaModel", b =>
                {
                    b.Property<int>("JuriCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JuriCodigo"), 1L, 1);

                    b.Property<bool?>("JuriEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("JuriEstadoOperacion")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JuriFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("JuriFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("JuriNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JuriCodigo");

                    b.ToTable("ClasJuridica");
                });

            modelBuilder.Entity("DomainLayer.Models.CoberturaModel", b =>
                {
                    b.Property<int>("CobeCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CobeCodigo"), 1L, 1);

                    b.Property<bool?>("CobeEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CobeFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CobeFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CobeNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CobeCodigo");

                    b.ToTable("Cobertura");
                });

            modelBuilder.Entity("DomainLayer.Models.ConceptoNotaModel", b =>
                {
                    b.Property<int>("ConoCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConoCodigo"), 1L, 1);

                    b.Property<bool?>("ConoEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConoFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConoFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConoCodigo");

                    b.ToTable("ConceptoNota");
                });

            modelBuilder.Entity("DomainLayer.Models.CondicionVentaModel", b =>
                {
                    b.Property<int>("CoveCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoveCodigo"), 1L, 1);

                    b.Property<bool?>("CoveEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CoveFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoveFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoveNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoveCodigo");

                    b.ToTable("CondicionVenta");
                });

            modelBuilder.Entity("DomainLayer.Models.CumModel", b =>
                {
                    b.Property<int>("CumsCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CumsCodigo"), 1L, 1);

                    b.Property<int>("CumsConsecutivo")
                        .HasColumnType("int");

                    b.Property<bool?>("CumsEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("CumsExpediente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CumsFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CumsFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CumsNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CumsCodigo");

                    b.ToTable("Cum");
                });

            modelBuilder.Entity("DomainLayer.Models.CupModel", b =>
                {
                    b.Property<int>("CupsCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CupsCodigo"), 1L, 1);

                    b.Property<bool?>("CupsEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CupsFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CupsFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CupsNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CupsCodigo");

                    b.ToTable("Cup");
                });

            modelBuilder.Entity("DomainLayer.Models.DeptoModel", b =>
                {
                    b.Property<int>("DeptoCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptoCodigo"), 1L, 1);

                    b.Property<bool?>("DeptoEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeptoFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeptoFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeptoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptoCodigo");

                    b.ToTable("Depto");
                });

            modelBuilder.Entity("DomainLayer.Models.EstadoDianFacturaModel", b =>
                {
                    b.Property<int>("EsfaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EsfaCodigo"), 1L, 1);

                    b.Property<bool?>("EsfaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EsfaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EsfaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("EsfaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EsfaCodigo");

                    b.ToTable("EstadoDianFactura");
                });

            modelBuilder.Entity("DomainLayer.Models.FactSaludTipoModel", b =>
                {
                    b.Property<int>("FasaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FasaCodigo"), 1L, 1);

                    b.Property<bool?>("FasaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FasaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FasaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FasaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FasaCodigo");

                    b.ToTable("FactSaludTipo");
                });

            modelBuilder.Entity("DomainLayer.Models.FormaPagoModel", b =>
                {
                    b.Property<int>("FopaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FopaCodigo"), 1L, 1);

                    b.Property<bool?>("FopaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FopaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FopaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FopaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FopaCodigo");

                    b.ToTable("FormaPago");
                });

            modelBuilder.Entity("DomainLayer.Models.ImpuestoModel", b =>
                {
                    b.Property<int>("ImpuCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImpuCodigo"), 1L, 1);

                    b.Property<bool?>("ImpuEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("ImpuEstadoOperacion")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ImpuFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ImpuFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImpuNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpuOperacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ImpuPorcentaje")
                        .IsRequired()
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ImpuCodigo");

                    b.ToTable("Impuesto");
                });

            modelBuilder.Entity("DomainLayer.Models.IumModel", b =>
                {
                    b.Property<int>("IumCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IumCodigo"), 1L, 1);

                    b.Property<bool?>("IumEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IumFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IumFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IumNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IumUnidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IumCodigo");

                    b.ToTable("Ium");
                });

            modelBuilder.Entity("DomainLayer.Models.LocalidadModel", b =>
                {
                    b.Property<int>("LocaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocaCodigo"), 1L, 1);

                    b.Property<int>("LocaCiudadCiudCodigo")
                        .HasColumnType("int");

                    b.Property<int>("LocaDeptoDeptoCodigo")
                        .HasColumnType("int");

                    b.Property<bool?>("LocaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LocaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LocaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocaCodigo");

                    b.HasIndex("LocaCiudadCiudCodigo");

                    b.HasIndex("LocaDeptoDeptoCodigo");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("DomainLayer.Models.ModalidadPagoModel", b =>
                {
                    b.Property<int>("MopaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MopaCodigo"), 1L, 1);

                    b.Property<bool?>("MopaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MopaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MopaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MopaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MopaCodigo");

                    b.ToTable("ModalidadPago");
                });

            modelBuilder.Entity("DomainLayer.Models.MonedaModel", b =>
                {
                    b.Property<int>("MoneCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoneCodigo"), 1L, 1);

                    b.Property<bool?>("MoneEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MoneFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MoneFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoneNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MoneCodigo");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("DomainLayer.Models.NumeracionResolucionModel", b =>
                {
                    b.Property<int>("NureCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NureCodigo"), 1L, 1);

                    b.Property<bool?>("NureEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NureFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NureFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NureNumeracionActual")
                        .HasColumnType("int");

                    b.HasKey("NureCodigo");

                    b.ToTable("numeracionResolucion");
                });

            modelBuilder.Entity("DomainLayer.Models.PaisModel", b =>
                {
                    b.Property<int>("PaisCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaisCodigo"), 1L, 1);

                    b.Property<bool?>("PaisEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaisFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaisFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaisCodigo");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("DomainLayer.Models.RegimenModel", b =>
                {
                    b.Property<int>("RegiCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegiCodigo"), 1L, 1);

                    b.Property<bool?>("RegiEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<bool?>("RegiEstadoOperacion")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegiFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegiFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegiNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegiCodigo");

                    b.ToTable("Regimen");
                });

            modelBuilder.Entity("DomainLayer.Models.RespFiscalModel", b =>
                {
                    b.Property<int>("RefiCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefiCodigo"), 1L, 1);

                    b.Property<bool?>("RefiEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RefiFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RefiFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefiNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefiCodigo");

                    b.ToTable("RespFiscal");
                });

            modelBuilder.Entity("DomainLayer.Models.RespTributariaModel", b =>
                {
                    b.Property<int>("RetrCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RetrCodigo"), 1L, 1);

                    b.Property<bool?>("RetrEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RetrFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RetrFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("RetrNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RetrCodigo");

                    b.ToTable("RespTributaria");
                });

            modelBuilder.Entity("DomainLayer.Models.ReteFuenteModel", b =>
                {
                    b.Property<int>("ReteCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReteCodigo"), 1L, 1);

                    b.Property<bool?>("ReteEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReteFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReteFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RetePorcentaje")
                        .IsRequired()
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ReteCodigo");

                    b.ToTable("ReteFuente");
                });

            modelBuilder.Entity("DomainLayer.Models.RolModel", b =>
                {
                    b.Property<int>("RolCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolCodigo"), 1L, 1);

                    b.Property<string>("RolDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RolEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RolFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RolFechaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("RolCodigo");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("DomainLayer.Models.RolUsuarioModel", b =>
                {
                    b.Property<int>("RousCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RousCodigo"), 1L, 1);

                    b.Property<bool?>("RousEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RousFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RousFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RousRol")
                        .HasColumnType("int");

                    b.Property<int>("RousUsuario")
                        .HasColumnType("int");

                    b.HasKey("RousCodigo");

                    b.HasIndex("RousRol");

                    b.HasIndex("RousUsuario");

                    b.ToTable("RolUsuario");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoArchivoRipsModel", b =>
                {
                    b.Property<int>("ArriCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArriCodigo"), 1L, 1);

                    b.Property<bool?>("ArriEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ArriFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArriFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArriNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArriCodigo");

                    b.ToTable("TipoArchivoRips");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoClienteModel", b =>
                {
                    b.Property<int>("TiclCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiclCodigo"), 1L, 1);

                    b.Property<bool?>("TiclEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TiclFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TiclFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TiclNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TiclCodigo");

                    b.ToTable("TipoCliente");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoCupModel", b =>
                {
                    b.Property<int>("TicuCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicuCodigo"), 1L, 1);

                    b.Property<bool?>("TicuEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TicuFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TicuFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TicuNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicuCodigo");

                    b.ToTable("TipoCup");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoDescuentoModel", b =>
                {
                    b.Property<int>("TideCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TideCodigo"), 1L, 1);

                    b.Property<bool?>("TideEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TideFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TideFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TideNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TideCodigo");

                    b.ToTable("TipoDescuento");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoDocElectrModel", b =>
                {
                    b.Property<int>("TidoCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TidoCodigo"), 1L, 1);

                    b.Property<bool?>("TidoEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TidoFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TidoFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TidoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TidoCodigo");

                    b.ToTable("TipoDocElectr");
                });

            modelBuilder.Entity("DomainLayer.Models.TipoIdModel", b =>
                {
                    b.Property<int>("TiidCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TiidCodigo"), 1L, 1);

                    b.Property<bool?>("TiidEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TiidFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TiidFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TiidNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TiidCodigo");

                    b.ToTable("TipoId");
                });

            modelBuilder.Entity("DomainLayer.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuaCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuaCodigo"), 1L, 1);

                    b.Property<bool?>("UsuaEstado")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsuaFechaCreacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsuaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuaIntentos")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("UsuaPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuaCodigo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DomainLayer.Models.CiudadModel", b =>
                {
                    b.HasOne("DomainLayer.Models.DeptoModel", "Depto")
                        .WithMany("Ciudades")
                        .HasForeignKey("CiudDepto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Depto");
                });

            modelBuilder.Entity("DomainLayer.Models.LocalidadModel", b =>
                {
                    b.HasOne("DomainLayer.Models.CiudadModel", "LocaCiudad")
                        .WithMany()
                        .HasForeignKey("LocaCiudadCiudCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.DeptoModel", "LocaDepto")
                        .WithMany()
                        .HasForeignKey("LocaDeptoDeptoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocaCiudad");

                    b.Navigation("LocaDepto");
                });

            modelBuilder.Entity("DomainLayer.Models.RolUsuarioModel", b =>
                {
                    b.HasOne("DomainLayer.Models.RolModel", "Rol")
                        .WithMany("Roles")
                        .HasForeignKey("RousRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainLayer.Models.UsuarioModel", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("RousUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DomainLayer.Models.DeptoModel", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("DomainLayer.Models.RolModel", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("DomainLayer.Models.UsuarioModel", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
