// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.Data;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231125001819_Rol")]
    partial class Rol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Models.RolModel", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolCodigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RolEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RolFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RolFechaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("DomainLayer.Models.RolesUsuarioModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool?>("RoleEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RoleFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RoleFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleRolRolId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleUsuarioUsuaId")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleRolRolId");

                    b.HasIndex("RoleUsuarioUsuaId");

                    b.ToTable("RolesUsuario");
                });

            modelBuilder.Entity("DomainLayer.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuaId"));

                    b.Property<bool?>("UsuaEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsuaFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsuaFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuaIntentos")
                        .HasColumnType("int");

                    b.Property<string>("UsuaPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuaUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuaId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DomainLayer.Models.RolesUsuarioModel", b =>
                {
                    b.HasOne("DomainLayer.Models.RolModel", "RoleRol")
                        .WithMany("RolUsuarios")
                        .HasForeignKey("RoleRolRolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomainLayer.Models.UsuarioModel", "RoleUsuario")
                        .WithMany("UsuRoles")
                        .HasForeignKey("RoleUsuarioUsuaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RoleRol");

                    b.Navigation("RoleUsuario");
                });

            modelBuilder.Entity("DomainLayer.Models.RolModel", b =>
                {
                    b.Navigation("RolUsuarios");
                });

            modelBuilder.Entity("DomainLayer.Models.UsuarioModel", b =>
                {
                    b.Navigation("UsuRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
